### [POST] sign up 
POST http://localhost:3001/api/auth/signup HTTP/1.1
content-type: application/json

{
  "email": "cloer@gmail.com",
  "nickname":"cloer",
  "password": "Password1!"
}

### [POST] sign in
POST http://localhost:3001/api/auth/signin HTTP/1.1
content-type: application/json

{
  "email":"cloer@gmail.com",
  "password":"Password1!"
}

### [GET] list of total rooms
GET http://localhost:3001/api/rooms HTTP/1.1
content-type: application/json

### [GET] list of rooms the user joined
GET http://localhost:3001/api/rooms/1 HTTP/1.1
content-type: application/json