### ✅ sign in 
### [POST] /api/auth 
POST http://localhost:3001/api/auth/ HTTP/1.1
content-type: application/json

{
  "email": "cloer@gmail.com",
  "password": "aA1!"
}

### ✅ sign out 
### [get] /api/auth
GET http://localhost:3001/api/auth/ HTTP/1.1
content-type: application/json

### ✅ sign up
### [POST] /api/users
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
  "email":"cloer1@gmail.com",
  "nickname":"cloer",
  "password":"Password1!"
}

### ✅ delete a user
### [DELETE] /api/users
DELETE http://localhost:3001/api/users HTTP/1.1
content-type: application/json

### ✅ create a new room
### [POST] /api/rooms
POST http://localhost:3001/api/rooms HTTP/1.1
content-type: application/json

{
  "title":"RoomId is 2!"
}

### ✅ join the room
### [GET] /api/users/in/:roomId
GET http://localhost:3001/api/users/in/2 HTTP/1.1
content-type: application/json

### ✅ leave the room
### [POST] /api/users/out/:roomId
GET http://localhost:3001/api/users/out/5 HTTP/1.1
content-type: application/json

### ✅ get list of total rooms
### [GET] /api/rooms
GET http://localhost:3001/api/rooms HTTP/1.1
content-type: application/json

### get list of rooms the user joined
### [GET] /api/rooms/:userId
GET http://localhost:3001/api/rooms/1 HTTP/1.1
content-type: application/json

### ✅ Not Found
### [GET] /wrong path
GET http://localhost:3001/wrongpath HTTP/1.1
content-type: application/json